### ISSUE TITLE
How to disable safeScripts?

### ISSUE THREAD

**Issue by linonetwo** [xStarbound/xStarbound#10]
I didn't see this in readme, also not in xsbinit.config, disable this because I want to use Stardust Core.

I also tried

```js
{
  "assetDirectories" : [
    "..\\assets\\",
    "..\\xsb-assets\\",
    "..\\mods\\"
  ],

  "storageDirectory" : "..\\storage\\",

  "assetsSettings" : {
    "pathIgnore" : [],
    "digestIgnore" : [
      ".*"
    ]
  },

  "defaultConfiguration" : {
    "allowAdminCommandsFromAnyone" : true,
    "anonymousConnectionsAreAdmin" : true
  },
  "safeScripts": false
}

**Comment by FezzedOne** [comment]
The `"safeScripts"` key is found in `xclient.config` for xClient or `xserver.config` for xServer. On Windows, these files are located in `C:\Program Files (x86)\Steam\steamapps\common\Starbound\storage\`.

This issue has been closed. If you still have issues with Stardust Core after disabling `"safeScripts"`, open a new issue.

**Comment by linonetwo** [comment]
This works.
