### ISSUE TITLE
Show error reason of not starting

### ISSUE THREAD

**Issue by linonetwo** [xStarbound/xStarbound#11]
After install and uninstall some mods, Steam may generate bad symlink on /mods folder, cause original game launcher show this kind of error:

![图片](https://github.com/xStarbound/xStarbound/assets/3746270/fe8b56c4-49ea-4b08-b6c5-97b76e3371d3)

![图片](https://github.com/xStarbound/xStarbound/assets/3746270/4798e88a-83b2-499f-bed6-79ce81b8b4e4)

(Also this is why I need Stardust Core, because Stardust Tech depends on it)

And xStarbound will quit immediately without showing errors, make it hard to find the problem.

**Comment by FezzedOne** [comment]
This is a Steam issue; report the bug to Valve. Closed because it's irrelevant to xStarbound itself.

**Comment by FezzedOne** [comment]
This is a Steam issue; report the bug to Valve. Closed because it's irrelevant to xStarbound itself.

**Comment by linonetwo** [comment]
The idea was show something so it won't silently failed. But this can also be read on the log so it is fine.
