### ISSUE TITLE
Humanoid enemy don't have hit box

### ISSUE THREAD

**Issue by linonetwo** [xStarbound/xStarbound#12]
While vanilla launcher can hit them. In xStarbound they can't be hit, so they become invincible. Ship member's attack also don't hit them, but enemy can hit me.
Both in mission map and planet dungeon. 

Non humanoid enemy works fine. I think this only happened to enemy that can beam up.

But maybe this is cause by some mod...

But I already remove all Partially compatible mods, it still don't work. And on vanilla launcher I can hit them.

**Comment by FezzedOne** [comment]
Please upload your `xclient.log`. If you're on an xStarbound server, also upload `xserver.log`.

If you're on Windows and have Starbound on Steam, these logs are most likely found in `C:\Program Files (x86)\Steam\steamapps\common\Starbound\storage\`.

If you're on Linux and have Starbound on Steam, the logs are most likely in `~/.local/share/Steam/steamapps/common/Starbound/storage/`.

**Comment by linonetwo** [comment]
[xclient.log](https://github.com/user-attachments/files/16175385/xclient.log)


I see

```
[19:29:02.991] [Error] Exception while calling script init: (LuaException) Error code 2, [string "/scripts/blshieldnpcutil.lua"]:12: bad argument #1 to 'randomseed' (number has no integer representation)
stack traceback:
	[C]: in ?
	[C]: in function 'math.randomseed'
	[string "/scripts/blshieldnpcutil.lua"]:12: in field 'init'
	[string "/stats/effects/randgenblshield/npcs/baserando..."]:27: in function <[string "/stats/effects/randgenblshield/npcs/baserando..."]:7>
```

Even when enable/disable the safeScripts

**Comment by linonetwo** [comment]
[starbound.log](https://github.com/user-attachments/files/16175464/starbound.log)

I also use vanilla client start for a reference. It seems doesn't have this error (while it will have other errors, which make gun not aimable, surprisingly xClient don't have this bug.)

**Comment by linonetwo** [comment]
Workaround for BL2Shield mod:

Unpack

```pwsh
G:\SteamLibrary\steamapps\common\Starbound\win32\asset_unpacker.exe "G:\SteamLibrary\steamapps\workshop\content\211820\2064881027\contents.pak" "UnpackedAssets"
```

(Modify all `math.randomseed(world.time())` to `math.randomseed(math.floor(world.time()))`, to suit it for xStarbound)

Repack

```pwsh
G:\SteamLibrary\steamapps\common\Starbound\win32\asset_packer.exe "G:\SteamLibrary\steamapps\workshop\content\211820\2064881027\UnpackedAssets" "contents.pak"
```

then it works

**Comment by FezzedOne** [comment]
Well, there's your fix. I suggest reporting this Lua 5.4 incompatibility bug to FelmastProMcLane, the author of BL2Shield. Not that he answers support requests, but oh well.
