### ISSUE TITLE
fatal error access violation detected when close game

### ISSUE THREAD

**Issue by DevilPaean** [xStarbound/xStarbound#17]
when click esc---save and quit, it appears this:
![QQ图片20240816212517](https://github.com/user-attachments/assets/d4d89208-1ec5-48fd-93dd-2d1692247949)
same error in these situations:
1. steam online, offline or close
2. safescipt true or false
3. disablerepack true or false
4. with or without chinese translation and font mod

[log.zip](https://github.com/user-attachments/files/16637650/log.zip)
[log with pdb.zip](https://github.com/user-attachments/files/16637738/log.with.pdb.zip)
save file: https://drive.google.com/file/d/15MfaBU09ZKN8SD_N3ghzZFH6wIrt5pQl/view?usp=drive_link
and after i reboot computer, the first time that i launch xclient.exe is ok. but the 2nd time i launch game, the error is appear

And if I have many quests, then game will lag. Is that normal? Using FU mod.

**Comment by FezzedOne** [comment]
> [log with pdb.zip](https://github.com/user-attachments/files/16637738/log.with.pdb.zip)

This log was from a session where you did **NOT** have the PDBs installed correctly. Put the PDB files **IN THE SAME FOLDER AS THE `.exe` FILES** and try again. Also **ensure the PDBs are for the SAME VERSION of xStarbound as the `.exe`s.**

**Comment by FezzedOne** [comment]
Also, I cannot access your save file because I don't have a Google Drive account. Please use another service that doesn't require logging in to download the file.

**Comment by DevilPaean** [comment]
like this? file are all from lask week version in release page.
![QQ图片20240817002617](https://github.com/user-attachments/assets/ba142679-c6c1-4894-a497-bd9d25a6fea9)

i'm using these mods and fu. (https://steamcommunity.com/sharedfiles/filedetails/?id=729480149)
[mods.zip](https://github.com/user-attachments/files/16639329/mods.zip)

this is my save. sorry i dont know which cloud drive dont need login in...
[新建压缩.zip](https://github.com/user-attachments/files/16639360/default.zip)
[新建压缩.zip](https://github.com/user-attachments/files/16639382/default.zip) change .zip to .z01
[新建压缩.zip](https://github.com/user-attachments/files/16639384/default.zip) change .zip to .z02

**Comment by Renkoto** [comment]
The file in the Google Drive link is set to private, please change the file's visibility setting.

**Comment by DevilPaean** [comment]
> The file in the Google Drive link is set to private, please change the file's visibility setting.

it should be ok. sorry my first time using google drive as uploader...

**Comment by DevilPaean** [comment]
it begin lag after i accept all quests.
if i delete quests to about 10 quests, then it's no lag.
i dont know if it's normal? because i search that a guy mentioned quest number make game lag in reddit.

**Comment by FezzedOne** [comment]
I can't replicate this crash on the Linux build, apparently. It's Windows-specific.

**Comment by DevilPaean** [comment]
I go to science outpost and then no error... seems that the error is caused by first planet?

**Comment by FezzedOne** [comment]
At least that's another data point. Note that I couldn't reproduce your crash on the garden world you were on.

**Comment by DevilPaean** [comment]
thanks your help anyway~~~~
