### ISSUE TITLE
Add Wayland information/support

### ISSUE THREAD

**Issue by emanueljg** [xStarbound/xStarbound#19]
Wayland is surprisingly easy to support natively for xStarbound, I got it working in just a few minutes. To support it, we just need to do 3 things:

- [ ] Use oSB's GLEW hack: https://github.com/OpenStarbound/OpenStarbound/commit/a75703085ebf0c28e3dd089f4ddcd716177afa21. This is needed because of https://github.com/nigels-com/glew/issues/172.
- [ ] Launch xclient with `SDL_VIDEODRIVER=wayland`, maybe create a new shellscript for this too?
- [ ] Document Wayland support

**Comment by FezzedOne** [comment]
I'll add this in the next point update. Thanks.
