### ISSUE TITLE
xSB-2 v2.3.7.1 crashes: Failed to find callback named: showVoicePlayers

### ISSUE THREAD

**Issue by dirbasti** [xStarbound/xStarbound#2]
Hi, 

I experienced that crash also with an older version. 

[xclient.log](https://github.com/FezzedOne/xSB-2/files/14332314/xclient.log)

Could you please give me some advice? Am I missing a prerequisite?

**Comment by FezzedOne** [comment]
Update your `xSBassets.pak` or `xSBassets/` folder to the latest version. I'm releasing a new update in a few minutes.
