### ISSUE TITLE
[BUG] Frackin Universe Mod - Power Relays and Batteries

### ISSUE THREAD

**Issue by megaStephenS** [xStarbound/xStarbound#24]
## Description

When playing with the Frackin Universe mod, there are wire items called power relays and batteries that transmit power to devices added by FU. But the power relays and batteries do not work.

If the power generator items are connected directly to devices via wire, it works. But if wired using power relays or batteries, power is not distributed or it powers up for a second then stops.

I've attached a screenshot of the setup that does not work. This exact setup works as intended in OpenStarbound. Thanks!

<img width="541" alt="Yu Long Zai Tian Screenshot 2024 11 16 - 19 03 37 47" src="https://github.com/user-attachments/assets/a439e294-cdd6-4fe0-80d2-7ee6e7dd712c">
[xclient.zip](https://github.com/user-attachments/files/17788214/xclient.zip)

**Comment by FezzedOne** [comment]
I need to see your `xclient.log` please.

**Comment by FezzedOne** [comment]
This setup works on xStarbound: 
![image](https://github.com/user-attachments/assets/6a43f2d6-550b-4927-8af8-caf4a69985e3)

**Comment by FezzedOne** [comment]
This setup with a power relay in the mix does *not* appear to work:
![image](https://github.com/user-attachments/assets/fb448880-b63b-4e4e-8ec5-8469cbb0dc49)
No errors or warnings in the log though.

**Comment by FezzedOne** [comment]
Take the battery out of the picture and the relay works now:
![image](https://github.com/user-attachments/assets/01166b34-e92f-4582-a06e-899ee0b37422)

**Comment by FezzedOne** [comment]
Can you test your setup against the new [v3.3.1r2 point update](https://github.com/xStarbound/xStarbound/releases/tag/v3.3.1r2)? This added a few extra Lua script compatibility fixes that *might* potentially affect wired objects in FU.

**Comment by megaStephenS** [comment]
Hey, just tried it and it's still having the same issues. I noticed that sometimes some wire connections work or sometimes all connections work for like 1/2 a second then shuts off. If I make less connections between in-game devices, it tends to work than if I make multiple connections. Uploaded the xlog below - thanks again!

[xclient.log](https://github.com/user-attachments/files/17919424/xclient.log)

**Comment by megaStephenS** [comment]
Side Note: Also tried the newest version, v3.3.1r3. Same results.

**Comment by FezzedOne** [comment]
> If I make less connections between in-game devices, it tends to work than if I make multiple connections.

It's something I've also noticed. Still have no clue why it's behaving this way. I checked and double-checked FU's scripts for any potential compatibility issues.

**Comment by FezzedOne** [comment]
This issue does not appear to affect vanilla logic gates used as relays.

**Comment by FezzedOne** [comment]
Okay, I managed to find the actual issue — it's a tiny script compatibility issue in FU's `fupower.lua` script that arises because that script doesn't explicitly use `jarray` on a table before sending that table through `world.callScriptedEntity` to other objects. xStarbound coerces values passed through `world.callScriptedEntity` into JSON when `"safeScripts"` is enabled, and in this case, it made a wrong assumption during the coercion — that a value is an object rather than an array, causing integer keys to be turned into string keys, which are ignored by a `for` loop in `fupower.lua` — so disabling `"safeScripts"` would fix your bug.

**Comment by FezzedOne** [comment]
This compatibility issue has been fixed in [Frackin Patch v1.1](https://github.com/xStarbound/xStarbound/releases/tag/v3.3.1r3-FPv1.1) — it's attached to the current xStarbound release. If you're hosting multiplayer, the patch is server/host-side.

**Issue resolved.**
