### ISSUE TITLE
[BUG] Sign animation not working

### ISSUE THREAD

**Issue by loveaabb** [xStarbound/xStarbound#27]
## Description

Signs created at EASEL with multiple frames do not animate, it only shows the first frame

## Reproduction steps

1. Go to the EASEL shop (the "DESIGN" booth) at The Outpost
2. Design a sign with multiple frames (design tutorial: https://starbounder.org/Guide:Animated_Signs)
3. Place the sign

**Comment by FezzedOne** [comment]
This should be fixed now alongside another sign animation issue in [v3.3.2](https://github.com/xStarbound/xStarbound/releases/tag/FPv1.1.1) (commit [38b857b](https://github.com/xStarbound/xStarbound/commit/38b857bf9d9a6ee725b7b0c718d24312ba01c212)). Reopen this issue if sign animations are still broken.
