### ISSUE TITLE
Help with installing

### ISSUE THREAD

**Issue by Rikopara** [xStarbound/xStarbound#3]
I tried to install xSB, but nothing changed ingame, so I guess I did installation process wrong.  What I did is:
1. Created `xsb-win64` folder, and put all the files from `windows.zip`
2. Also downloaded and placed here `xSBassets.pak`
3. Created `steam_appid` with my steam id, because there wasn't any other id file.
4. Started `xclient.exe`

I may be a little dummy, thanks for help in advice. 
Platform: Windows 11 23H2 64 bit

**Comment by FezzedOne** [comment]
Resolved on the Discord server.
