### ISSUE TITLE
Linux: No cursor displayed on xSB client window

### ISSUE THREAD

**Issue by Vetpetmon** [xStarbound/xStarbound#6]
System details:
- OS: Pop!_OS 22.04 LTS x86_64
- Kernel: 6.6.10-76060610-generic
- DE: GNOME 42.5
- WM: Mutter 
- GPU: NVIDIA GeForce GTX 1660

Expected behavior:
- A cursor should display, if not a custom one, then at least the system cursor should display

Actual behavior: 
- Cursor disappears entirely when hovering over the xSB client.

Note: Issue happens after the game is loaded

**Comment by FezzedOne** [comment]
I don't have issues with Wayland cursors on my end, but then again, I use Plasma 6, not GNOME. For right now, I'd suggest `env -u WAYLAND_DISPLAY ./xclient.sh`.

**Comment by Vetpetmon** [comment]
I am on X11, not wayland

**Comment by FezzedOne** [comment]
Huh. Let me check something then.

**Comment by FezzedOne** [comment]
The cursor works just fine in XWayland, and I know it was functioning fine when I used X11. Can you give me your `xclient.log` file, and if you can, a screen recording?

**Comment by FezzedOne** [comment]
Just tested on X11, and the cursor renders as it should for me. I would like to see your full `xclient.log`, mod list, `xclient.config`, `xsbinit.config` and preferably also a screen recording.

**Comment by FezzedOne** [comment]
This issue should be fixed as of xStarbound v3.0. If you're still getting cursor rendering issues, enter `/cursor off` in the chat when you get in game.
