### ISSUE TITLE
Vehicle Handling Issue

### ISSUE THREAD

**Issue by dfdffish** [xStarbound/xStarbound#8]
I recall bringing up an issue previously on Discord regarding **the weird handling of vehicles** that deviates from the behavior in the vanilla version of Starbound. I do remember that this issue was supposed to have been resolved in subsequent updates.

However, upon my recent return to the game and using the latest version of xSB-2, I have discovered that the problem persists. It appears that in xSB-2, vehicle handling is predominantly server-side, contrasting with the client-side handling in the original game. This results in vehicles exhibiting a noticeable delay in response to player inputs.

And this gets even worse if joined as a client in server, I tested by hosting a local x-server and connecting directly through 127.0.0.1

The issue is quite reproducible: **simply drive a vehicle in xSB-2 and compare it with one in the vanilla game**. The difference is obvious and significantly impacts the gameplay experience, making certain vehicle-related missions—such as those in Shellguard—frustratingly difficult, and at times, nearly unplayable.

It's worth mentioning that this issue does not seem to affect mechs for some reason. The handling of mechs in xSB-2 remains consistent with that in the vanilla version, which confused me.

I hope I haven't misunderstood any aspects of this issue. I would greatly appreciate it if you could look into this matter. Thank you in advance for your attention to this. :D

**Comment by FezzedOne** [comment]
I'll have a look into this vehicle lag issue. Seems something yucky _might_ be going on with network interpolation there.

**Comment by FezzedOne** [comment]
Okay, first of all, can I see a list of all mods you have loaded? If you're running Futara's Dragon Engine or Futara's Dragon Race, that is known to cause serious lag issues.

It's because xStarbound — yes, the name has been changed — fixes a bug where the `"entityUpdateDelta"` parameter set by FDE/FDR in `$assets/worldserver.config` wasn't used, which mean it's, well, now used, causing entity updates to happen only once every half of a second, making everything feel laggy as shit.

**Comment by dfdffish** [comment]
[xclient.log](https://github.com/user-attachments/files/15992841/xclient.log)
Ok Sure. Here is my xclient.log in case I missed something, And no I don't have Futara's Dragon Engine installed. 

And I tried removing all my mods and did some tests:

(1)xclient singleplayer, with no mod installed: **vehicle minor latency**, which is kinda tolerable.
(2)xclient multiplayer using x-server as host, connected as a client, with no mod: **vehicle severe latency**
(3)xclient multiplayer using vanilla server as host, connected as a client, with no mod: **vehicle severe latency**

(4)vanilla singleplayer, with no mods installed: **no lag**
(5)vanilla multiplayer, using x-server as host, connected as a client, with no mods: **no lag**

It feels like **"Input Delaying"** or **lack of "Lag Compensation**"?

I think it may have something to do with how xclient handles vehicles? If it's not obvious for you, try something like a gunship-type vehicle? the movement and the attack are just so weird, especially playing on a server as a client.

**Comment by dfdffish** [comment]
[xclient.log](https://github.com/user-attachments/files/15992841/xclient.log)
Ok Sure. Here is my xclient.log in case I missed something, And no I don't have Futara's Dragon Engine installed. 

And I tried removing all my mods and did some tests:

(1)xclient singleplayer, with no mod installed: **vehicle minor latency**, which is kinda tolerable.
(2)xclient multiplayer using x-server as host, connected as a client, with no mod: **vehicle severe latency**
(3)xclient multiplayer using vanilla server as host, connected as a client, with no mod: **vehicle severe latency**

(4)vanilla singleplayer, with no mods installed: **no lag**
(5)vanilla multiplayer, using x-server as host, connected as a client, with no mods: **no lag**

It feels like **"Input Delaying" or no "Lag Compensation".**

I think it may have something to do with how xclient handles vehicles? If it's not obvious for you, try something like a gunship-type vehicle? the movement and the attack are just so weird, especially playing on a server as a client.

**Comment by dfdffish** [comment]
[xclient.log](https://github.com/user-attachments/files/15992841/xclient.log)
Ok Sure. Here is my xclient.log in case I missed something, And no I don't have Futara's Dragon Engine installed. 

And I tried removing all my mods and did some tests:

(1)xclient singleplayer, with no mod installed: **vehicle minor latency**, which is kinda tolerable.
(2)xclient multiplayer using x-server as host, connected as a client, with no mod: **vehicle severe latency**
(3)xclient multiplayer using vanilla server as host, connected as a client, with no mod: **vehicle severe latency**

(4)vanilla singleplayer, with no mods installed: **no lag**
(5)vanilla multiplayer, using x-server as host, connected as a client, with no mods: **no lag**

It feels like **"Input Delaying" or no "Lag Compensation".**

I think it may have something to do with how xclient handles vehicles? If it's not obvious for you, try something like a gunship-type vehicle? the movement and the attack are just so weird, especially playing on a server as a client.

**Comment by FezzedOne** [comment]
I'm currently working on debugging another bug, but I'll get to yours in a few minutes. It's pretty obvious from the description that your bug is client-side though.

**Comment by dfdffish** [comment]
Okay. Appreciated :D, I'm about to head off to bed. I'll check your message when I wake up.

**Comment by FezzedOne** [comment]
I haven't come any closer to a real solution, but using the command `/timescale 20.0` just after you get into a vehicle does help *while you're on a server*. Don't forget to use `/timescale 1.0` when you get out of the vehicle. This does imply that multiplying the game's internal «lag time» for slave vehicle controls by 0.05 or something similar might help as a workaround for this issue.

**Comment by dfdffish** [comment]
Okay. So it's basically a temporary solution by speeding up the client? Well it does help but everything else like sfx and vfx get crazy after this. 

Thanks for notifying me. I guess I'll just wait patiently for the real solution then. :)

**Comment by FezzedOne** [comment]
Well, to be more precise, my temporary stopgap fix would affect *only* the «lag time» for vehicle controls, unlike `/timescale`.

**Comment by FezzedOne** [comment]
So I'm in the middle of trying some other potential fixes for vehicle lag. I'll post back with the results.

**Comment by dfdffish** [comment]
Good to hear! :D

**Comment by FezzedOne** [comment]
The bug is now fixed. Turns out the network interpolation code was receiving delta times in *seconds* instead of ticks. Since a tick is 1/60 second, that made network interpolation feel really «laggy» and «slow», which is what caused the vehicle «lag» (among other things). The v3.0 update which contains this bugfix (and lots and lots of other stuff!) will be out in a few minutes.

**Comment by dfdffish** [comment]
Wow! Thank you so much, Can't wait to try the new client! XD
